### ISSUE TITLE
Panic on assertion failed: bitwidth <= 16

### ISSUE THREAD

**Issue by neosilky** [RazrFalcon/usvg#20]
Found using honggfuzz.

Looks like an assertion fail in a dependency but I triggered it through this library so I've opened this issue to track.

Triggered by:
```
\x1F\x8B\x08\xC1\x7B\x7B\x7B\x7B\x7B\x7B\x7B\x7B\x7B\x7B\x7B\x7B\x7B\x7B\x7B\x7B\x7B\x7B\x80\x80\x80\x80\x7B\x7B\x7B\x7B\x7B\x7B\x97\x7B\x7B\x7B\x86\x27\xEB\x60\xA7\xA8\x46\x6E\x1F\x33\x51\x5C\x34\xE0\xD2\x2E\xE8\x0C\x19\x1D\x3D\x3C\xFD\x3B\x6A\xFA\x63\xDF\x28\x87\x86\xF2\xA6\xAC\x87\x86\xF2\xA6\xAC\xD5
```

```
thread 'main' panicked at 'assertion failed: bitwidth <= 16', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.15/src/bit.rs:114:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:397
   6: <libflate::deflate::decode::Decoder<R>>::read_compressed_block
             at /home/user/.cargo/git/checkouts/usvg-91b2c264f2c5b922/eb4b3bc/<panic macros>:3
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.15/src/bit.rs:108
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.15/src/deflate/symbol.rs:209
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.15/src/deflate/symbol.rs:188
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.15/src/deflate/decode.rs:101
   7: <libflate::deflate::decode::Decoder<R> as std::io::Read>::read
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.15/src/deflate/decode.rs:172
   8: <libflate::gzip::Decoder<R> as std::io::Read>::read
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.15/src/gzip.rs:949
   9: std::io::read_to_end
             at /checkout/src/libstd/io/mod.rs:379
  10: std::io::Read::read_to_string::{{closure}}
             at /checkout/src/libstd/io/mod.rs:657
  11: std::io::append_to_string
             at /checkout/src/libstd/io/mod.rs:343
  12: std::io::Read::read_to_string
             at /checkout/src/libstd/io/mod.rs:657
  13: usvg::tree::io::deflate
             at /home/user/.cargo/git/checkouts/usvg-91b2c264f2c5b922/eb4b3bc/src/tree/io.rs:50
  14: usvg::tree::Tree::from_data
             at /home/user/.cargo/git/checkouts/usvg-91b2c264f2c5b922/eb4b3bc/src/tree/mod.rs:50
  15: usvg_parse_tree::main::{{closure}}
             at /home/user/daniel/targets/common/src/lib.rs:1025
             at fuzzer-honggfuzz/src/bin/usvg_parse_tree.rs:8
  16: honggfuzz::fuzz
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/honggfuzz-0.5.20/src/lib.rs:301
  17: usvg_parse_tree::main
             at fuzzer-honggfuzz/src/bin/usvg_parse_tree.rs:7
  18: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  19: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  20: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  21: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  22: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  23: main
  24: __libc_start_main
  25: _start
```

**Comment by RazrFalcon** [comment]
This is [libflate](https://github.com/sile/libflate) bug. You should report this to their bug tracker.
