### ISSUE TITLE
Panic on assertion failed: (left == right)

### ISSUE THREAD

**Issue by neosilky** [RazrFalcon/usvg#21]
Found using honggfuzz.

Looks like an assertion fail in a dependency but I triggered it through this library so I've opened this issue to track.

Triggered by:
```
\x1F\x8B\x08\xC1\x7B\x7B\x7B\x7B\x7B\xFC\x5D\x2D\xDC\x08\xC1\x7B\x7B\x7B\x7B\x7B\xFC\x5D\x2D\xDC\x08\xC1\x7B\x7F\x7B\x7B\x7B\xFC\x5D\x2D\xDC\x69\x32\x48\x22\x5A\x81\x81\x42\x42\x81\x7E\x81\x81\x81\x81\xF2\x17
```

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `108`,
 right: `14`', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.15/src/deflate/symbol.rs:397:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: <libflate::deflate::symbol::DynamicHuffmanCodec as libflate::deflate::symbol::HuffmanCodec>::load
             at /home/user/.cargo/git/checkouts/usvg-91b2c264f2c5b922/eb4b3bc/<panic macros>:8
   7: <libflate::deflate::decode::Decoder<R>>::read_compressed_block
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.15/src/deflate/decode.rs:99
   8: <libflate::deflate::decode::Decoder<R> as std::io::Read>::read
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.15/src/deflate/decode.rs:176
   9: <libflate::gzip::Decoder<R> as std::io::Read>::read
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.15/src/gzip.rs:949
  10: std::io::read_to_end
             at /checkout/src/libstd/io/mod.rs:379
  11: std::io::Read::read_to_string::{{closure}}
             at /checkout/src/libstd/io/mod.rs:657
  12: std::io::append_to_string
             at /checkout/src/libstd/io/mod.rs:343
  13: std::io::Read::read_to_string
             at /checkout/src/libstd/io/mod.rs:657
  14: usvg::tree::io::deflate
             at /home/user/.cargo/git/checkouts/usvg-91b2c264f2c5b922/eb4b3bc/src/tree/io.rs:50
  15: usvg::tree::Tree::from_data
             at /home/user/.cargo/git/checkouts/usvg-91b2c264f2c5b922/eb4b3bc/src/tree/mod.rs:50
  16: usvg_parse_tree::main::{{closure}}
             at /home/user/daniel/targets/common/src/lib.rs:1025
             at fuzzer-honggfuzz/src/bin/usvg_parse_tree.rs:8
  17: honggfuzz::fuzz
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/honggfuzz-0.5.20/src/lib.rs:301
  18: usvg_parse_tree::main
             at fuzzer-honggfuzz/src/bin/usvg_parse_tree.rs:7
  19: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  20: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  21: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  22: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  23: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  24: main
  25: __libc_start_main
  26: _start
```

**Comment by RazrFalcon** [comment]
This is [libflate](https://github.com/sile/libflate) bug. You should report this to their bug tracker.
